# Generated by Django 5.1.4 on 2025-08-29 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_categorias_itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='tb_fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('telefone1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('uf', models.CharField(blank=True, max_length=25, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=80, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=80, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8)),
                ('observacao', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='tb_itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('LT', 'Litro'), ('CX', 'Caixa'), ('MT', 'Metro')], max_length=2)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('estoque_maximo', models.PositiveIntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Inativo', max_length=8)),
                ('cadastrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastrador_usuario', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='Suprimentos.tb_categorias_itens')),
                ('ultima_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tb_rg_entradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_entrada', models.CharField(choices=[('Compra', 'Compra'), ('Doação', 'Doação'), ('Produção', 'Produção'), ('Ajuste', 'Ajuste')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_und', models.CharField(max_length=10)),
                ('valor_total', models.CharField(max_length=10)),
                ('num_nota', models.PositiveIntegerField()),
                ('lote', models.CharField(max_length=10)),
                ('validade_lote', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cadastrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='Suprimentos.tb_fornecedores')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='Suprimentos.tb_marcas')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Suprimentos.tb_itens')),
            ],
        ),
    ]
