# Generated by Django 5.1.4 on 2025-08-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suprimentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_fornecedores',
            old_name='localidad',
            new_name='localidade',
        ),
        migrations.AlterField(
            model_name='tb_rg_entradas',
            name='tip_entrada',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Doação', 'Doação'), ('Produção', 'Produção')], max_length=10),
        ),
    ]
