# Generated by Django 5.1.4 on 2025-08-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suprimentos', '0002_rename_localidad_tb_fornecedores_localidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_rg_entradas',
            name='lote',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tb_rg_entradas',
            name='num_nota',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
