# Generated by Django 5.1.4 on 2025-08-30 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suprimentos', '0003_alter_tb_rg_entradas_lote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=10, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('quantidade_atual', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='Suprimentos.tb_itens')),
            ],
        ),
    ]
