# Generated by Django 5.1.4 on 2025-09-05 00:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suprimentos', '0004_tb_estoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_rg_entradas',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_entrada', to='Suprimentos.tb_itens'),
        ),
        migrations.CreateModel(
            name='tb_rm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm', models.CharField(editable=False, max_length=10, unique=True)),
                ('data_solic', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tb_autorizacoes_saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Autorizado', 'Autorizado'), ('Negado', 'Negado')], default='Pendente', max_length=12)),
                ('data_autor', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('quant_liberada', models.PositiveIntegerField(blank=True, null=True)),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacoes_saida', to=settings.AUTH_USER_MODEL)),
                ('rm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes', to='Suprimentos.tb_rm')),
            ],
        ),
        migrations.CreateModel(
            name='tb_soli_materiais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_solicitada', models.PositiveIntegerField()),
                ('tip_saida', models.CharField(choices=[('Consumo', 'Consumo'), ('Perda', 'Perda'), ('Avariado', 'Avariado'), ('Outro', 'Outro')], max_length=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Suprimentos.tb_itens')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Suprimentos.tb_rm')),
            ],
        ),
    ]
