# Generated by Django 5.1.4 on 2025-09-05 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suprimentos', '0005_alter_tb_rg_entradas_material_tb_rm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_autorizacoes_saida',
            old_name='rm',
            new_name='Nrm',
        ),
    ]
