# Generated by Django 5.1.4 on 2025-09-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suprimentos', '0006_rename_rm_tb_autorizacoes_saida_nrm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_autorizacoes_saida',
            name='quant_liberada',
        ),
        migrations.AddField(
            model_name='tb_soli_materiais',
            name='quant_liberada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
