# Generated by Django 5.1.4 on 2025-09-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suprimentos', '0007_remove_tb_autorizacoes_saida_quant_liberada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_autorizacoes_saida',
            name='data_autor',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
