# Generated by Django 5.1.4 on 2025-10-03 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suprimentos', '0008_alter_tb_autorizacoes_saida_data_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_estoque',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='Suprimentos.tb_marcas'),
            preserve_default=False,
        ),
    ]
