# Generated by Django 5.1.3 on 2024-11-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_assis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('data_nasci', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome_mae', models.CharField(max_length=70)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=8)),
            ],
        ),
    ]
