# Generated by Django 5.1.3 on 2024-11-17 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_assis_hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_assis', models.CharField(max_length=100)),
                ('data_assis', models.DateField()),
                ('local_assis', models.TextField(blank=True, null=True)),
                ('assistido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='AssisManage.tb_assis')),
            ],
        ),
    ]
