# Generated by Django 5.1.3 on 2024-11-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0002_tb_assis_hist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_assis',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
