# Generated by Django 5.1.3 on 2024-11-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0003_alter_tb_assis_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_assis',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
