# Generated by Django 5.1.3 on 2024-11-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0004_alter_tb_assis_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_assis',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='data_nasci',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='logradouro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='numero',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
