# Generated by Django 5.1.3 on 2024-12-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0005_alter_tb_assis_bairro_alter_tb_assis_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_assis_hist',
            name='assistido',
        ),
        migrations.RemoveField(
            model_name='tb_assis_hist',
            name='data_assis',
        ),
        migrations.RemoveField(
            model_name='tb_assis_hist',
            name='local_assis',
        ),
        migrations.RemoveField(
            model_name='tb_assis_hist',
            name='tipo_assis',
        ),
        migrations.AddField(
            model_name='tb_assis_hist',
            name='data',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tb_assis_hist',
            name='local',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tb_assis_hist',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tb_assis_hist',
            name='tip_assistencia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
