# Generated by Django 5.1.2 on 2025-02-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0006_remove_tb_assis_hist_assistido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_tip_assistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_assis', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tb_assis',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tb_assis',
            name='tip_assistencia',
            field=models.ManyToManyField(blank=True, related_name='tipos_assis', to='AssisManage.tb_tip_assistencias'),
        ),
    ]
