# Generated by Django 5.1.4 on 2025-06-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0007_tb_tip_assistencias_tb_assis_telefone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_assis_hist',
            name='numero',
        ),
    ]
