# Generated by Django 5.1.4 on 2025-06-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0008_remove_tb_assis_hist_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_locais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tb_assis_hist',
            name='id_assistido',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tb_assis_hist',
            name='tip_assistencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tipos_assistencia', to='AssisManage.tb_tip_assistencias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tb_assis_hist',
            name='local',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='locais', to='AssisManage.tb_locais'),
        ),
    ]
