# Generated by Django 5.1.4 on 2025-07-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0010_tb_assis_ultima_alteracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_assis',
            name='observacao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='bairro',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='logradouro',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
