# Generated by Django 5.1.4 on 2025-07-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0011_tb_assis_observacao_alter_tb_assis_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_assis',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
