# Generated by Django 5.1.4 on 2025-07-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0012_tb_assis_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_assis',
            name='seg_telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
