# Generated by Django 5.1.4 on 2025-07-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0013_tb_assis_seg_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_assis',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
