# Generated by Django 5.1.4 on 2025-07-31 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0014_alter_tb_assis_observacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_senhas_lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lote', models.CharField(max_length=20)),
                ('intervalo', models.CharField(max_length=100)),
                ('tipo_assistencia', models.CharField(max_length=25)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tb_assis',
            name='senha_ativa',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='tb_assis_hist',
            name='atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tb_assis_hist',
            name='senha',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
