# Generated by Django 5.1.4 on 2025-08-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0015_tb_senhas_lote_tb_assis_senha_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_senhas_lote',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='Ativo', max_length=10, verbose_name='Status'),
        ),
    ]
