# Generated by Django 5.1.4 on 2025-08-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0016_tb_senhas_lote_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_assis',
            name='senha_ativa',
        ),
    ]
