# Generated by Django 5.1.4 on 2025-08-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0017_remove_tb_assis_senha_ativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_senhas_assis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistido_id', models.IntegerField()),
                ('senha', models.IntegerField(unique=True)),
                ('lote_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senhas', to='AssisManage.tb_senhas_lote')),
            ],
        ),
    ]
