# Generated by Django 5.1.4 on 2025-08-05 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0019_tb_senhas_lote_ultima_alteracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_senhas_assis',
            name='tipo_assistencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='senhas', to='AssisManage.tb_tip_assistencias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tb_senhas_assis',
            name='senha',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tb_senhas_lote',
            name='tipo_assistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='AssisManage.tb_tip_assistencias'),
        ),
    ]
