# Generated by Django 5.1.4 on 2025-08-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0020_tb_senhas_assis_tipo_assistencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_vinculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Ativo', 'ativo'), ('Inativo', 'inativo')], default='Ativo', max_length=10, verbose_name='Status')),
            ],
        ),
        migrations.AlterField(
            model_name='tb_senhas_lote',
            name='status',
            field=models.CharField(choices=[('Ativo', 'ativo'), ('Inativo', 'inativo')], default='Ativo', max_length=10, verbose_name='Status'),
        ),
    ]
