# Generated by Django 5.1.4 on 2025-08-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0021_tb_vinculos_alter_tb_senhas_lote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_assis',
            name='vinculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='AssisManage.tb_vinculos'),
        ),
    ]
