# Generated by Django 5.1.4 on 2025-08-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0022_tb_assis_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_assis',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
