# Generated by Django 5.1.4 on 2025-08-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0023_alter_tb_assis_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_senhas_lote',
            name='mensagem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
