# Generated by Django 5.1.4 on 2025-08-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0024_tb_senhas_lote_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_assis',
            name='vinculo',
        ),
        migrations.RemoveField(
            model_name='tb_senhas_lote',
            name='mensagem',
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tb_senhas_lote',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='Ativo', max_length=10, verbose_name='Status'),
        ),
    ]
