# Generated by Django 5.1.4 on 2025-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0025_remove_tb_assis_vinculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_senhas_lote',
            name='mensagem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
