# Generated by Django 5.1.4 on 2025-08-08 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0026_tb_senhas_lote_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_assis',
            name='vinculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='AssisManage.tb_vinculos'),
        ),
        migrations.AlterField(
            model_name='tb_assis',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]