# Generated by Django 5.1.4 on 2025-09-23 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0027_tb_assis_vinculo_alter_tb_assis_data_cadastro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_senhas_assis',
            name='assistido_id',
        ),
        migrations.RemoveField(
            model_name='tb_senhas_assis',
            name='tipo_assistencia',
        ),
        migrations.AddField(
            model_name='tb_senhas_assis',
            name='assistido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assistidos', to='AssisManage.tb_assis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_senhas_assis',
            name='data_entrega',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tb_senhas_assis',
            name='data_entrega_confi',
            field=models.DateTimeField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tb_senhas_assis',
            name='entregador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregador_cesta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tb_senhas_assis',
            name='status',
            field=models.CharField(choices=[('Emitida', 'Emitida'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Emitida', max_length=12, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='tb_lote_senhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lote', models.CharField(max_length=20)),
                ('id_inicial', models.CharField(max_length=8)),
                ('id_final', models.CharField(max_length=8)),
                ('senhas_validas', models.IntegerField(default=0)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('mensagem', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10, verbose_name='Status')),
                ('tipo_assistencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistencias_lote', to='AssisManage.tb_tip_assistencias')),
                ('ultima_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastro_senhas_lote', to=settings.AUTH_USER_MODEL)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_lote', to='AssisManage.tb_vinculos')),
            ],
        ),
        migrations.AlterField(
            model_name='tb_senhas_assis',
            name='lote_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='senhas', to='AssisManage.tb_lote_senhas'),
        ),
        migrations.DeleteModel(
            name='tb_senhas_lote',
        ),
    ]
