# Generated by Django 5.1.4 on 2025-09-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0028_remove_tb_senhas_assis_assistido_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_lote_senhas',
            name='mensagem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
