# Generated by Django 5.1.4 on 2025-09-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssisManage', '0029_alter_tb_lote_senhas_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_lote_senhas',
            name='id_final',
        ),
        migrations.RemoveField(
            model_name='tb_lote_senhas',
            name='id_inicial',
        ),
    ]
