# Generated by Django 5.1.2 on 2025-02-23 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitadoresList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitador', models.CharField(max_length=50, verbose_name='Facilitador')),
            ],
        ),
        migrations.CreateModel(
            name='HistAtendATF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_1_vez', models.PositiveIntegerField(default=0, verbose_name='Quant. 1° vez')),
                ('quant_retorno', models.PositiveIntegerField(default=0, verbose_name='Quant. Retorno')),
                ('data', models.DateField(verbose_name='Data')),
                ('facilitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='ATF.facilitadoreslist')),
            ],
        ),
    ]
