# Generated by Django 5.1.4 on 2025-06-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoATF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
