# Generated by Django 5.1.4 on 2025-06-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATF', '0002_arquivoatf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoatf',
            name='imagem',
            field=models.ImageField(upload_to='ATF/img/Prontuarios/'),
        ),
    ]
