# Generated by Django 5.1.4 on 2025-07-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATF', '0003_alter_arquivoatf_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitadoreslist',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
    ]
